// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_buffer.proto

#ifndef PROTOBUF_INCLUDED_test_5fbuffer_2eproto
#define PROTOBUF_INCLUDED_test_5fbuffer_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_5fbuffer_2eproto 

namespace protobuf_test_5fbuffer_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_5fbuffer_2eproto
namespace TestBuffer {
class TestData;
class TestDataDefaultTypeInternal;
extern TestDataDefaultTypeInternal _TestData_default_instance_;
class TestData_Record;
class TestData_RecordDefaultTypeInternal;
extern TestData_RecordDefaultTypeInternal _TestData_Record_default_instance_;
}  // namespace TestBuffer
namespace google {
namespace protobuf {
template<> ::TestBuffer::TestData* Arena::CreateMaybeMessage<::TestBuffer::TestData>(Arena*);
template<> ::TestBuffer::TestData_Record* Arena::CreateMaybeMessage<::TestBuffer::TestData_Record>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace TestBuffer {

// ===================================================================

class TestData_Record : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TestBuffer.TestData.Record) */ {
 public:
  TestData_Record();
  virtual ~TestData_Record();

  TestData_Record(const TestData_Record& from);

  inline TestData_Record& operator=(const TestData_Record& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestData_Record(TestData_Record&& from) noexcept
    : TestData_Record() {
    *this = ::std::move(from);
  }

  inline TestData_Record& operator=(TestData_Record&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestData_Record& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestData_Record* internal_default_instance() {
    return reinterpret_cast<const TestData_Record*>(
               &_TestData_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TestData_Record* other);
  friend void swap(TestData_Record& a, TestData_Record& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestData_Record* New() const final {
    return CreateMaybeMessage<TestData_Record>(NULL);
  }

  TestData_Record* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestData_Record>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestData_Record& from);
  void MergeFrom(const TestData_Record& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestData_Record* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes text = 11;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 11;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const void* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // optional int32 text_len = 12;
  bool has_text_len() const;
  void clear_text_len();
  static const int kTextLenFieldNumber = 12;
  ::google::protobuf::int32 text_len() const;
  void set_text_len(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestBuffer.TestData.Record)
 private:
  void set_has_text();
  void clear_has_text();
  void set_has_text_len();
  void clear_has_text_len();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::google::protobuf::int32 text_len_;
  friend struct ::protobuf_test_5fbuffer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TestData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TestBuffer.TestData) */ {
 public:
  TestData();
  virtual ~TestData();

  TestData(const TestData& from);

  inline TestData& operator=(const TestData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestData(TestData&& from) noexcept
    : TestData() {
    *this = ::std::move(from);
  }

  inline TestData& operator=(TestData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestData* internal_default_instance() {
    return reinterpret_cast<const TestData*>(
               &_TestData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TestData* other);
  friend void swap(TestData& a, TestData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestData* New() const final {
    return CreateMaybeMessage<TestData>(NULL);
  }

  TestData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestData& from);
  void MergeFrom(const TestData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef TestData_Record Record;

  // accessors -------------------------------------------------------

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .TestBuffer.TestData.Record record = 3;
  bool has_record() const;
  void clear_record();
  static const int kRecordFieldNumber = 3;
  private:
  const ::TestBuffer::TestData_Record& _internal_record() const;
  public:
  const ::TestBuffer::TestData_Record& record() const;
  ::TestBuffer::TestData_Record* release_record();
  ::TestBuffer::TestData_Record* mutable_record();
  void set_allocated_record(::TestBuffer::TestData_Record* record);

  // optional int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestBuffer.TestData)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();
  void set_has_record();
  void clear_has_record();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::TestBuffer::TestData_Record* record_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_test_5fbuffer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestData_Record

// optional bytes text = 11;
inline bool TestData_Record::has_text() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestData_Record::set_has_text() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestData_Record::clear_has_text() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestData_Record::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& TestData_Record::text() const {
  // @@protoc_insertion_point(field_get:TestBuffer.TestData.Record.text)
  return text_.GetNoArena();
}
inline void TestData_Record::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TestBuffer.TestData.Record.text)
}
#if LANG_CXX11
inline void TestData_Record::set_text(::std::string&& value) {
  set_has_text();
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TestBuffer.TestData.Record.text)
}
#endif
inline void TestData_Record::set_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TestBuffer.TestData.Record.text)
}
inline void TestData_Record::set_text(const void* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TestBuffer.TestData.Record.text)
}
inline ::std::string* TestData_Record::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:TestBuffer.TestData.Record.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestData_Record::release_text() {
  // @@protoc_insertion_point(field_release:TestBuffer.TestData.Record.text)
  if (!has_text()) {
    return NULL;
  }
  clear_has_text();
  return text_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestData_Record::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:TestBuffer.TestData.Record.text)
}

// optional int32 text_len = 12;
inline bool TestData_Record::has_text_len() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestData_Record::set_has_text_len() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestData_Record::clear_has_text_len() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestData_Record::clear_text_len() {
  text_len_ = 0;
  clear_has_text_len();
}
inline ::google::protobuf::int32 TestData_Record::text_len() const {
  // @@protoc_insertion_point(field_get:TestBuffer.TestData.Record.text_len)
  return text_len_;
}
inline void TestData_Record::set_text_len(::google::protobuf::int32 value) {
  set_has_text_len();
  text_len_ = value;
  // @@protoc_insertion_point(field_set:TestBuffer.TestData.Record.text_len)
}

// -------------------------------------------------------------------

// TestData

// optional int32 id = 1;
inline bool TestData::has_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TestData::set_has_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TestData::clear_has_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TestData::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 TestData::id() const {
  // @@protoc_insertion_point(field_get:TestBuffer.TestData.id)
  return id_;
}
inline void TestData::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TestBuffer.TestData.id)
}

// optional string name = 2;
inline bool TestData::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestData::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestData::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& TestData::name() const {
  // @@protoc_insertion_point(field_get:TestBuffer.TestData.name)
  return name_.GetNoArena();
}
inline void TestData::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TestBuffer.TestData.name)
}
#if LANG_CXX11
inline void TestData::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TestBuffer.TestData.name)
}
#endif
inline void TestData::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TestBuffer.TestData.name)
}
inline void TestData::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TestBuffer.TestData.name)
}
inline ::std::string* TestData::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:TestBuffer.TestData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestData::release_name() {
  // @@protoc_insertion_point(field_release:TestBuffer.TestData.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:TestBuffer.TestData.name)
}

// optional .TestBuffer.TestData.Record record = 3;
inline bool TestData::has_record() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestData::set_has_record() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestData::clear_has_record() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestData::clear_record() {
  if (record_ != NULL) record_->Clear();
  clear_has_record();
}
inline const ::TestBuffer::TestData_Record& TestData::_internal_record() const {
  return *record_;
}
inline const ::TestBuffer::TestData_Record& TestData::record() const {
  const ::TestBuffer::TestData_Record* p = record_;
  // @@protoc_insertion_point(field_get:TestBuffer.TestData.record)
  return p != NULL ? *p : *reinterpret_cast<const ::TestBuffer::TestData_Record*>(
      &::TestBuffer::_TestData_Record_default_instance_);
}
inline ::TestBuffer::TestData_Record* TestData::release_record() {
  // @@protoc_insertion_point(field_release:TestBuffer.TestData.record)
  clear_has_record();
  ::TestBuffer::TestData_Record* temp = record_;
  record_ = NULL;
  return temp;
}
inline ::TestBuffer::TestData_Record* TestData::mutable_record() {
  set_has_record();
  if (record_ == NULL) {
    auto* p = CreateMaybeMessage<::TestBuffer::TestData_Record>(GetArenaNoVirtual());
    record_ = p;
  }
  // @@protoc_insertion_point(field_mutable:TestBuffer.TestData.record)
  return record_;
}
inline void TestData::set_allocated_record(::TestBuffer::TestData_Record* record) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete record_;
  }
  if (record) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      record = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, record, submessage_arena);
    }
    set_has_record();
  } else {
    clear_has_record();
  }
  record_ = record;
  // @@protoc_insertion_point(field_set_allocated:TestBuffer.TestData.record)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace TestBuffer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_5fbuffer_2eproto
